default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: restaurant_app_development

test:
  <<: *default
  database: restaurant_app_test

production:
  <<: *default
  database: restaurant_app_production
  username: restaurant_app
  password: <%= ENV['RESTAURANT_APP_DATABASE_PASSWORD'] %>
