# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201d077f8cf5dc249e528acecb1e57f55f9370d47c8a15b7467298dab767cc87b9ec476c55fe2817db43051067949b35da88cc90b384b0cf5e1afb8ff5eb6e58

test:
  secret_key_base: 49c8a5a96ff4d2a5741bf9aee2cb1e4e09bdf6538935bc3f3ea4139b8a02fe9fa75ecc1f617faa7facf24534ff4381f34af2a2450db35e8389233d895441b886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
